# Generated by Django 2.2.12 on 2020-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.IntegerField()),
                ('executor_role', models.IntegerField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.TimeField(auto_now_add=True)),
                ('person_id', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
