# Generated by Django 2.2.12 on 2020-04-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200430_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='person_id',
            field=models.CharField(default='missing', max_length=30),
        ),
        migrations.AlterField(
            model_name='finance',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
