# Generated by Django 2.2.12 on 2020-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20200430_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
