# Generated by Django 2.2.12 on 2020-04-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('clerk_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('password', models.CharField(default='SBPJ', max_length=256)),
                ('salt', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=10)),
                ('c_time', models.TimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=256)),
                ('menu_name', models.CharField(default='Edit Book', max_length=256, unique=True)),
                ('role_menu_url', models.CharField(default='1', max_length=256)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clerk_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.Clerk')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.Role')),
            ],
        ),
    ]
