# Generated by Django 2.2.12 on 2020-05-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_menu_url', models.CharField(max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Import_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='library.Books')),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clerk.Clerk')),
            ],
        ),
    ]
