# Generated by Django 2.2.12 on 2020-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_import_order_permission_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_cate',
            name='name',
            field=models.CharField(default='lalala', max_length=256),
            preserve_default=False,
        ),
    ]
